name: Ruby Tests

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

env:
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password

jobs:
  test:
    name: Tests

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: password
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          bundle install --jobs 4 --retry 3

      - name: Setup database
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate

      - name: Run tests
        run: |
          bundle exec rake
